### ISSUE TITLE
Newt hangs/freezes if it cannot connect to Wifi

### ISSUE THREAD

**Issue by darianbjohnson** [Phambili-Tech/Newt_Display#13]
Add a timeout (or retry logic) if Newt cannot connect to wifi (this occurs when performing a periodic data refresh).

**Comment by andyshinn** [comment]
I was going to post that my Newt seems to freeze (the time doesn't increment and it is unresponsive). Is this possibly the same bug?

**Comment by darianbjohnson** [comment]
I think it’s the same bug, but not 100% sure (it happens intermittently for me). I’m going to add a WiFi timeout that should address the problem (or at least rule out unresponsive WiFi connections) as a cause.

**Comment by andyshinn** [comment]
Ooof... i spent a while reading over https://github.com/espressif/arduino-esp32/issues/653 but couldn't really make out if it was actually fixed or not. It did look like maybe it wasn't being enabled on ESP32 devices: https://github.com/tzapu/WiFiManager/blob/58baeaba6f0558199b4696ccfb8c005e813c352a/WiFiManager.cpp#L3725-L3738

**Comment by darianbjohnson** [comment]
Thanks @andyshinn - I'll look into this. I'm thinking of adding a wifi icon in the corner when the device connects... if there is a freeze then we'll know if was during an attempted/failed wifi connection

**Comment by andyshinn** [comment]
More info: I got a small LiPo battery and when it is running off the battery it works fine (has been going for days). But when I plug it into the USB-C for charging or powering it will freeze after an hour or two.

**Comment by darianbjohnson** [comment]
Fix in 1.1.0-RC-1 available for testing

**Comment by darianbjohnson** [comment]
Passed beta
