### ISSUE TITLE
Newt stop clock when internet was disabled

### ISSUE THREAD

**Issue by rrubanov** [Phambili-Tech/Newt_Display#27]
Clock on Newt stoped when internet service was down (wifi was alive). Device just froze. No reactions on buttons ether. Turning off from power helped when internet service was back.

**Comment by andypiper** [comment]
Ah! This sounds like the issue I've seen a couple of times in the past couple of days (also being discussed [here](https://github.com/Phambili-Tech/Newt_Display/discussions/25#discussioncomment-3406570)).

**Comment by darianbjohnson** [comment]
Passed beta
