### ISSUE TITLE
Add missing doc step to install espressif board support in ardunio

### ISSUE THREAD

**Issue by mikeyyuen** [Phambili-Tech/Newt_Display#28]
Currenty documentation on https://phambili.tech/newt/ misses some steps for getting the arduino IDE to work.

# Missing steps are

Configure the Espressif Boards in the Board Manager (if you've not already) by

1. Opening the Preferences in the Arduino IDE
2. Under Additional Board Manager URLs add the following it it doesn't already exist.
    
    ```
    https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
    ```
    
    If you have existing values in the URL list, you can add this one to the end of the list (note the list is comma seperated).
3. Click ok once added.
4. Under the Tools menu, choose `Boards` -> `Boards Manager`
5. Search for `esp32` then click install. This may take a few minutes.
6. Once the install is complete close the board manager. You can now find the Newt's board under `Tools` -> `Boards` -> `ESP32 Arduino` -> `ESP32S2 Native USB`

**Comment by darianbjohnson** [comment]
Thanks @mikeyyuen - I'll get the documentation updated by the end of the month (Aug 2022)

**Comment by darianbjohnson** [comment]
Updated on wiki. Phambili/tech now references wiki for instructions
