### ISSUE TITLE
Request: server-side code

### ISSUE THREAD

**Issue by andypiper** [Phambili-Tech/Newt_Display#3]
At the moment, this code depends on a server-side HTTP and MQTT service. Could the code for this be published?

**Comment by andypiper** [comment]
I've started to document what I've discovered about it in my repo fork [here](https://github.com/andypiper/newt_display).

**Comment by andypiper** [comment]
My issue https://github.com/andypiper/Newt_Display/issues/3 depends on knowing more about how the AQ data is sourced.

**Comment by andypiper** [comment]
Also [issue #4](https://github.com/andypiper/Newt_Display/issues/4) in my fork wants to improve the geolocation accuracy (right now my Newt thinks it is ~140 miles away from its actual location). If I could stand up an HTTP/MQTT server to be an alternate for the main one I could experiment with improving accuracy of some of these data points.

Also, enabling multiple or alternative backends in general would be useful - could be a backup if the main server is down or inaccessible, or provide different data.

**Comment by darianbjohnson** [comment]
I've been thinking a lot about how to make the source data more transparent for end users.... the quick and dirty thing to do is to get to source code available for people to look at. I'll try to handle that this weekend.

**Comment by andypiper** [comment]
Thanks - sorry for the deluge of issues / discussion - as you can tell, I’m excited to get hands-on and help here 🙂

**Comment by darianbjohnson** [comment]
Documentation and Link to source code (just the nodeJS code - not the libraries)
https://github.com/Phambili-Tech/Newt_Display/wiki/MQTT-API-Summary

**Comment by darianbjohnson** [comment]
Just starting documentation... so it'll evolve over time

**Comment by darianbjohnson** [comment]
Uploaded to github with required documentation
