### ISSUE TITLE
Source code and build instruction?

### ISSUE THREAD

**Issue by koocotte** [Phambili-Tech/Newt_Display#30]
Hello,

I'm looking for the source-code. Is it https://github.com/Phambili-Tech/Newt_Display ? I only found 1.0.1 but my Newt is at 1.0.2

src/ contain only file about the RV3028 realtime clock and is 4 month old
examples/Newt/Newt.ino include a lot of file not provided. It looks like the main file but it include a lot of files not provided. 

Is there something to manage builds? Lib dependencies? A manual to update from a custom build?

**Comment by koocotte** [comment]
Sorry, this is mostly redundant with #18

**Comment by darianbjohnson** [comment]
The codebase for 1.0.1 is the same as 1.0.2 (I had to do an emergency fix to recompile and push the binary - due to a defect in the esp32 library). I'm doing to close this issue and track it in [18](https://github.com/Phambili-Tech/Newt_Display/issues/18)
