### ISSUE TITLE
Add informations to settings

### ISSUE THREAD

**Issue by koocotte** [Phambili-Tech/Newt_Display#31]
Hello,

I suggest to add Wifi SSID name and IP address in the "Settings" page. (I did not found how it is done in the source code).

**Comment by darianbjohnson** [comment]
I think I can get this into the next release. Great call out!

**Comment by darianbjohnson** [comment]
In 1.1.0-RC - available for testing

**Comment by darianbjohnson** [comment]
Passed beta
