### ISSUE TITLE
version 1.0.1?

### ISSUE THREAD

**Issue by andypiper** [Phambili-Tech/Newt_Display#4]
The repo here builds a firmware version of 1.0.0 - is there a 1.0.1 available (the onscreen upgrade messages seem to indicate that there is, but the downloadable binary from S3 is also marked 1.0.0)

**Comment by darianbjohnson** [comment]
Great catch Andy - I released version 1.0.1 a few weeks ago, and have yet to get that version of the code into Github (it's a minor fix to resolve a big with obtaining Air Quality measurements). I'll try to get the latest version pushed out in the next day or so.

**Comment by darianbjohnson** [comment]
The latest version is uploaded and available (both here and via Arduino).
