### ISSUE TITLE
IP-based location not fine-grained/accurate enough, need a way to set location

### ISSUE THREAD

**Issue by kantarjiev** [Phambili-Tech/Newt_Display#49]
I'm in Palo Alto, but the location lookup puts me in Walnut Creek. Normally I wouldn't care, but the weather is wildly different between Palo Alto and Walnut Creek!

It would be nice to be able to set the location, either by ZIP or coarse-grained lat/lon

**Comment by darianbjohnson** [comment]
I'm working on a server-side portal that lets user's manually set the location, timezone, and all other settings. Still a ways out from being implemented...

**Comment by hmeyer** [comment]
+1 in this!

**Comment by darianbjohnson** [comment]
Hey guys; I'm going to close this as a duplicate - it's being tracked/worked as part of Issue #5
