### ISSUE TITLE
Display issue: blinking and low-contrast modes

### ISSUE THREAD

**Issue by phubbard** [Phambili-Tech/Newt_Display#50]
On 1.1.0 and now 1.1.3 firmware, my (new) Newt toggles between high and low contrast at seemingly random intervals. I’ll attach an animated GIF showing the behavior. I could handle the blink, but then much of the time the display goes to low contrast which is quite difficult to read. Any ideas most welcome.
![Made with Live GIF](https://user-images.githubusercontent.com/157158/194359354-6fae8161-8ffb-4a28-9e4e-a060c95aad28.gif)

**Comment by darianbjohnson** [comment]
Wow - that's a first. I wonder if the issue is actually HW related. Has this always been the case (the blinking, or the "fading"). Has this always been the case with your Newt?

**Comment by darianbjohnson** [comment]
And - does the fading/blinking occur when you are interacting with the screen (toggling menus. etc)? Or does it only occur when the device is "at rest"?

**Comment by phubbard** [comment]
It’s always done it. The display does go to high contrast when I press the menu button and usually reverts to low contrast after a bit. Happy to ship it to you if you want to root cause it out. Sent from my iPhoneOn Oct 6, 2022, at 9:24 AM, Darian Johnson ***@***.***> wrote:﻿
And - does the fading/blinking occur when you are interacting with the screen (toggling menus. etc)? Or does it only occur when the device is "at rest"?

**Comment by phubbard** [comment]
Yes, that’d be great.

**Comment by darianbjohnson** [comment]
Hey - I just shot an email to you on steps to replace your unit. Let me know if you don't see an email from me.

**Comment by darianbjohnson** [comment]
Hardware issue; closed.
