### ISSUE TITLE
Suggestion: enable GH Discussions?

### ISSUE THREAD

**Issue by andypiper** [Phambili-Tech/Newt_Display#8]
At the moment there’s no place (that I’m aware of) for Newt users and those interested in supporting development to share ideas, apart from in GH Issues. Would you consider enabling Discussions on this repository, or setting up some other community space?

**Comment by darianbjohnson** [comment]
I just enabled the feature. Let's try things out here - and if it doesn't work for us, then maybe we look at something else (Slack, Discord, etc).

**Comment by andypiper** [comment]
Thanks, let's close this and get chatting over there! Appreciate the willingness to create the space.
